title: Kait documentation
description: Capability-oriented AI and ML execution environments for Buildkite.
url: https://alexhraber.github.io
baseurl: /kait
markdown: kramdown
permalink: pretty
kramdown:
  input: GFM
